############################################################
# dist
############################################################
FROM ossrs/httpx:1 AS dist

EXPOSE 80 443

ADD zh-cn.tar.bz2 /usr/local/srs-docs/
ADD en-us.tar.bz2 /usr/local/srs-docs/
RUN cd /usr/local/srs-docs && ln -sf . lts && du -sh * && \
  du -sh zh-cn/* && du -sh en-us/*

WORKDIR /usr/local
CMD ["./bin/httpx-static", \
    "-http", "80", "-root", "./srs-docs", \
    "-no-redirect-index", "true" \
  ]
